### ISSUE TITLE
Google Play Services

### ISSUE THREAD

**Issue by mehrdad-abdoli** [butomo1989/docker-android#106]
Operating System: 
Ubuntu 16.04

Docker Image:
butomo1989/docker-android-x86-8.1

Docker Version:  
18.03.0-ce, build 0520e24

Docker-compose version (Only if you use it):  
1.20.1, build 5d8c71b

Docker Command to start docker-android:  
docker-compose up  -d
  
## Expected Behavior
Google play service be updated by [utils.sh](https://github.com/butomo1989/docker-android/blob/master/src/utils.sh#L29)

## Actual Behavior
Google play services can not be updated
here is the log error:
`adb: failed to install /root/google_play_services.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.google.android.gms sig                          natures do not match the previously installed version; ignoring!]`

**Comment by butomo1989** [comment]
yes, I need to change to google_apis, because play store image is a production image, so I cannot execute adb root to modify the emulator. could you help me to be able to run both google apks in the new image? @mehrdad-abdoli

**Comment by mehrdad-abdoli** [comment]
@butomo1989 
the script utils.sh works if disable change_language_if_needed

**Comment by butomo1989** [comment]
Thank you @mehrdad-abdoli I will take a look of it later.
The inital goal of the project is not only for Appium and I need it for different purpose as well.

**Comment by butomo1989** [comment]
disable that method do not fix the issue. are you sure that it fix the issue @mehrdad-abdoli ? could you retry it and describe the step here?

**Comment by mehrdad-abdoli** [comment]
@butomo1989  as I said in https://github.com/butomo1989/docker-android/issues/106#issuecomment-410439857   IMG_TYPE must be **google_apis_playstore**

**Comment by butomo1989** [comment]
then we need to find another way, because that image is production image and I cannot use root access to add other feature @mehrdad-abdoli
