### ISSUE TITLE
Run this container on Google Cloud.

### ISSUE THREAD

**Issue by pedrolarva** [butomo1989/docker-android#117]
Hello Gays!!!

i'm try to run this container on google cloud nested VM, but not working... 

Android loading... loading... loading... but not open.

Any ideia...?

**Comment by pedrolarva** [comment]
for more details...

I create Linux Centos VM in google cloud, install docker in the last version and run command:
`docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container butomo1989/docker-android-x86-8.1
`
And not work... 

Nested virtualization is enable...
`# grep -cw vmx /proc/cpuinfo 
4`

**Comment by butomo1989** [comment]
Please follow the instruction from PR #122
