### ISSUE TITLE
Issue on name formatting (Nexus 6 P)

### ISSUE THREAD

**Issue by rad96** [butomo1989/docker-android#121]
**Operating System:** 

Ubuntu 18.04

**Docker Image:**

butomo1989/docker-android-x86-8.0

**Docker Version:** 

Version:          18.06.1-ce

**Docker Command to start docker-android:**  

docker run --privileged -d -p 6080:6080 -p 4723:4723 -v /test:/test -e DEVICE='NEXUS 6P' -e APPIUM=true -e CONNECT_TO_GRID=true -e APPIUM_HOST=172.17.0.1 -e APPIUM_PORT=4723 -e SELENIUM_HOST=172.17.0.1 -e SELENIUM_PORT=4444 --name android0 butomo1989/docker-android-x86-8.0
  
## Expected Behavior

Appium and android emulator starting

## Actual Behavior

Appium and android emulator not starting
noVNC display only black screen
But when i change Device in docker run command to 'Nexus 6P' - it worked as expected

**Comment by rad96** [comment]
So, cat /var/log/supervisor/docker-android.stderr.log say the error is "No Device found matching --device NEXUS 6P"
but, if Nexus 6P work well, i think the error is only device string formatting in app.py

**Comment by butomo1989** [comment]
could you maybe help to fix it @rad96 ? it would be great.

**Comment by rad96** [comment]
i think it better be fixed on my side
