### ISSUE TITLE
The emulator has no google `Play Store` app

### ISSUE THREAD

**Issue by jetlv** [butomo1989/docker-android#126]
Operating System: 
CentOS 7.2

Docker Image:
butomo1989/docker-android-x86-7.1.1

Docker Version:  
18.09.0-beta3

Docker Command to start docker-android:  
docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -p 4723:4723 -e DEVICE="Samsung Galaxy S6" -e APPIUM=true --name v81 butomo1989/docker-android-x86-7.1.1
  
## Expected Behavior
Should have play store app as per the document

## Actual Behavior
The running android container doesn't have **Play Store**, but has Play Movie and Play Music, so does Google play service. But my test case need to start from play store searching.  I tried to manually install an play store apk but failed with message like 

> Package Conflicts with an existing Package

Tried to directly start by Appium but throws error like 'cannot uninstall com.android.vending'. (com.android.vending is app package of Play store)

![google](https://user-images.githubusercontent.com/13062041/47147682-59cf8380-d301-11e8-99d9-621cd5929dc6.png)

**Comment by lddd** [comment]
Same here, what was the solution?

**Comment by marad9016100** [comment]
Same here.
@jetlv Could you kindly share the solution?
