### ISSUE TITLE
how to change the display resolution

### ISSUE THREAD

**Issue by guozhanxian** [butomo1989/docker-android#132]
Operating System: centos7

Docker Image:
butomo1989/docker-android-x86-9.0

Docker Version:  
Docker version 18.09.0

I want to know how to change the display resolution. 
![2](https://user-images.githubusercontent.com/1329731/49722595-14e02180-fca0-11e8-859c-917edacdaf72.PNG)

**Comment by diemol** [comment]
Hi @guozhanxian,

The display resolution is given by the layout of the skin, see for example the [S6](https://github.com/butomo1989/docker-android/blob/master/devices/skins/samsung_galaxy_s6/layout#L49). You need to go there and change it yourself for the desired size. 

If that does not work, also try to modify the `config.ini` of the device, where the screen resolution is also mentioned. I think in this project it should be located under `/root/.android/avd/{theDevice}.avd/config.ini`.

**Comment by diemol** [comment]
You can also change the dpi if you want, check https://stackoverflow.com/questions/4791943/emulating-density-of-320-dpi-on-android-emulator
