### ISSUE TITLE
Startup issues on macOS Sierra

### ISSUE THREAD

**Issue by hursevich** [butomo1989/docker-android#21]
Hello, 
I'm really amazed by idea of dockerizing Android emulators along with Appium. I managed to run the docker-compose.yml according to README. Unfortunately during the next attempts of starting emulators I'm getting unhealthy status for emulator containers but still selenium instances are visible in grid: 

45cbde2532cd        butomo1989/docker-android-arm-7.1.1   "/bin/sh -c '/usr/..."   About an hour ago   Up About an hour (unhealthy)   4723/tcp, 5554-5555/tcp, 0.0.0.0:32769->6080/tcp   dockerandroid_samsung_galaxy_web_7.1.1_1
8bc4270ee96c        butomo1989/docker-android-arm-5.1.1   "/bin/sh -c '/usr/..."   About an hour ago   Up About an hour (unhealthy)   4723/tcp, 5554-5555/tcp, 0.0.0.0:32768->6080/tcp   dockerandroid_samsung_galaxy_web_5.1.1_1
159fa0d15aff        butomo1989/docker-android-arm-7.1.1   "/bin/sh -c '/usr/..."   About an hour ago   Up About an hour (unhealthy)   4723/tcp, 5554-5555/tcp, 0.0.0.0:32770->6080/tcp   dockerandroid_nexus_7.1.1_1
05480ed33c9d        selenium/hub:3.4.0                    "/opt/bin/entry_po..."   About an hour ago   Up About an hour               0.0.0.0:4444->4444/tcp                             dockerandroid_selenium_hub_1

When I open VNC via browser, I'm able to see emulator with loading Android but it never finish. The same situation repeats with Linux x86 image (tested on Ubuntu 16.04). Do you have any idea? I've removed all images and containers and reinstalled once again but nothing helps. I'm able to start single emulator from time to time but mostly it stays in unhealthy status.

**Comment by butomo1989** [comment]
Hi @hursevich ,

Thank you for opening this issue. Could you maybe join https://gitter.im/butomo1989/docker-android so we can discuss this issue there? because I think it might not related about the docker image (it might be because of your computer spec or configuration).

**Comment by butomo1989** [comment]
I'll close this issue because there is no further response here and also from gitter. Please feel free to reopen this issue.
