### ISSUE TITLE
Support android 8.0.0 (API 26) and 8.1.0 (API 27)

### ISSUE THREAD

**Issue by butomo1989** [butomo1989/docker-android#24]

**Comment by v3g3t4x** [comment]
When the support for new Android ?

**Comment by butomo1989** [comment]
Hi @v3g3t4x ,

I am working on something else at the moment, but it would be great if you can help us in this improvement and create a PR for it.

**Comment by JoeSSS** [comment]
Can be closed :)

**Comment by butomo1989** [comment]
@JoeSSS sure, I will close if after I release the new version.

**Comment by butomo1989** [comment]
Fixed in [release 1.1](https://github.com/butomo1989/docker-android/releases/tag/1.1)
