### ISSUE TITLE
How can downgrade appium version

### ISSUE THREAD

**Issue by mehrdad-abdoli** [butomo1989/docker-android#26]
I need to downgrade Appium version to 1.6.5  for some reasons .
How can it be done in docker-compose ?

**Comment by butomo1989** [comment]
Hi @mehrdad-abdoli ,

docker-android will always use the newest version of appium. You cannot downgrade it through docker-compose, but you can do it by going inside running docker-container and downgrade appium manually. it would be great if you can report that bug that you have to https://github.com/appium/appium so you can use the newest version of appium in the future.

**Comment by mehrdad-abdoli** [comment]
@butomo1989 
thanks I  have fixed it
