### ISSUE TITLE
does this support native app automation as well ?

### ISSUE THREAD

**Issue by vikramvi** [butomo1989/docker-android#29]
@butomo1989  please clarify if I can use this for native android app automation as well ?

Or it only used for mobile browser web UI automation ?

**Comment by alanbueno** [comment]
Hi @vikramvi, I'm coding automation for native apps and running on these emulated devices.
It works very well.

**Comment by vikramvi** [comment]
@alanbueno can you please explain your setup using this container based emualtor ?

My current setup is as follows

- bring up available android emulators
- start appium server
- start selenium hub and register nodes
- run tests in parallel with TestNG

**Comment by butomo1989** [comment]
Hi @vikramvi ,

I will close this PR because it is not a bug. maybe we can discuss about it in our group chat: https://gitter.im/butomo1989/docker-android

**Comment by vikramvi** [comment]
@alanbueno can you please clarify as per my last comment ?

**Comment by alanbueno** [comment]
Hi @vikramvi, sure. I'll answer on our group chat: https://gitter.im/butomo1989/docker-android
