### ISSUE TITLE
After Reset /  Reboot emulator didn't come up 

### ISSUE THREAD

**Issue by vikramvi** [butomo1989/docker-android#30]
As per README connected to one of the android emulator container from web browser.

Later tried options Reset, Reboot but even after few minutes didn't see emulator 

It will be nice if buttons can be disabled or show some message to user what's happening with emulator at present 

Please review

**Comment by dimasaryo** [comment]
It seems that `FileExists` exception is raised during `prepare_avd` process when the container restarted. So, the next line won't be executed. I manage to resolve that using force symlink method. Please see [fix FileExists error on prepare avd](https://github.com/dimasaryo/docker-android/pull/1)

**Comment by thelittlefireman** [comment]
Already done in release-08 branch #28
