### ISSUE TITLE
compose file -  selenium grid and docker-android container as nodes related issue

### ISSUE THREAD

**Issue by vikramvi** [butomo1989/docker-android#33]
below is the output after start up of compose file

```
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                         PORTS                                              NAMES
269f4689b2f2        butomo1989/docker-android-arm-7.1.1   "/bin/sh -c '/usr/..."   About an hour ago   Up About an hour (healthy)     4723/tcp, 5554-5555/tcp, 0.0.0.0:32770->6080/tcp   downloads_nexus_7.1.1_1
dd9dacf8600e        selenium/hub:3.4.0                    "/opt/bin/entry_po..."   About an hour ago   Up About an hour               0.0.0.0:4444->4444/tcp                             downloads_selenium_hub_1
282ba472d724        butomo1989/docker-android-arm-5.1.1   "/bin/sh -c '/usr/..."   About an hour ago   Up About an hour (unhealthy)   4723/tcp, 5554-5555/tcp, 0.0.0.0:32769->6080/tcp   downloads_samsung_galaxy_web_5.1.1_1
ab58889a898a        butomo1989/docker-android-arm-7.1.1   "/bin/sh -c '/usr/..."   About an hour ago   Up About an hour (unhealthy)   4723/tcp, 5554-5555/tcp, 0.0.0.0:32768->6080/tcp   downloads_samsung_galaxy_web_7.1.1_1
```

**Issue 1**
- all the nodes are showing as unhealthy 
 
**Issue 2**
- post VNC could see only 1 emulator, other 2 VNC sessions show appium server console

**Issue 3**
- adb connect hub_ip_address:5555
unable to connect to hub_ip_address:5555: Connection refused

Please review

**Comment by butomo1989** [comment]
HI @vikramvi , 

I think it is because of your RAM, could you check how many RAM is free in your laptop?

**Comment by mike75rock** [comment]
Hi, I ran docker-compose.yml on an instance of 32 GB RAM, and 16 CPU.
The same issue happens: the container status is unhealy and the emulator won't show up.

Any idea how this can be fixed?

Can it be run on Ubuntu Server at all?

Is there a specific hardware configuration?
