### ISSUE TITLE
Request to share the Dockerfile for the images

### ISSUE THREAD

**Issue by sqavenky** [butomo1989/docker-android#38]
Request Dockerfile for the images. I did not see any Dockerfile in your github repo.
Just curious why on the run with privileged part.
Also What are ports that are exposed. Is 6080 port a VNC port?
Thanks.

**Comment by thelittlefireman** [comment]
hi,
DockerFiles are her : https://github.com/butomo1989/docker-android/tree/master/docker

A DockerFile is not always named "dockerfile"

**Comment by sqavenky** [comment]
Thanks that helps. :-)
