### ISSUE TITLE
Emulator doesn't manage to boot in time in case of CI scenarios

### ISSUE THREAD

**Issue by andrcuns** [butomo1989/docker-android#4]
In case if this container is used in some sort of CI setup for automated test execution, tests start executing before the android in emulator is actually booted up.
It is possible to delay test execution within test set up it self but would not be so convenient if deploying multiple containers with selenium grid via docker-compose for example.
Would You consider adding a check for avd boot_complete during container start?

**Comment by elgalu** [comment]
SGTM :+1: What [I do in docker-selenium](https://github.com/elgalu/docker-selenium) is to

    docker exec grid wait_all_done 10s

This will active wait up to 10 seconds for the container to be ready for tests but will finish as soon as is ready. This script can also be used as a HEALTHCHECK instruction.

So you guys could do something similar for this image, e.g.

    docker exec android-container healthcheck.sh 1m

And inside that `healthcheck.sh` you put all the logic to wait for what's needed, avd boot_complete and so on.

So users can be sure that after that the container is ready to be used for testing.

**Comment by butomo1989** [comment]
could you maybe help me to fix this issue? @andrcuns

**Comment by andrcuns** [comment]
I have some ideas based on @elgalu excellent suggestion. I will try to test it out :)

**Comment by butomo1989** [comment]
I will close this PR, I have already included the implementation in release [0.5](https://github.com/butomo1989/docker-android/releases/tag/0.5)
