### ISSUE TITLE
appium random error Could not find app apk

### ISSUE THREAD

**Issue by mehrdad-abdoli** [butomo1989/docker-android#40]
hi
On android 5.0 , 5.1 and 6  appium tests has random behavior and throw such a error randomly:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find app apk at /root/tmp/myapp.apk
I have checked and Volume mounteded correctly it works some times as 60%
what is its reason?
where can I see appium logs in containers? there is no appium log in /var/log/supervisor/

**Comment by butomo1989** [comment]
Hi, @mehrdad-abdoli ,

Right now the appium log is not stored. it is just printed in the vnc. so for now you can see the logs by accessing vnc to see why this error occurred. I hope it helps. but in the future I can update docker-android to store appium logs.
