### ISSUE TITLE
video file naming

### ISSUE THREAD

**Issue by mehrdad-abdoli** [butomo1989/docker-android#43]
Hi
thanks for your great job and new video recording feautures .
How can i made build and test name so can change the test video file to be appended to test results.
I am using robot framework and python.
I use zalenium for web

**Comment by butomo1989** [comment]
Hi @mehrdad-abdoli , 

Thank you, happy to hear that this project helps you. no, I don’t have this feature right now.

**Comment by mehrdad-abdoli** [comment]
I do it myself by editing src/record.sh:
function start() {
    PR="$(curl -s localhost:4723/wd/hub/sessions | jq -r '.value[0].capabilities.PR')"
    name="$(curl -s localhost:4723/wd/hub/sessions | jq -r '.value[0].capabilities.name').mp4"
    mkdir -p $VIDEO_PATH/$PR
    echo "Start video recording"
    ffmpeg -video_size 1599x899 -framerate 15 -f x11grab -i $DISPLAY $VIDEO_PATH/$PR/$name -y
}

and send PR and name as capabilitiesin test run

for record.sh in compose file I added this volume:
- /home/record.sh:/root/src/record.sh

**Comment by butomo1989** [comment]
Hi @mehrdad-abdoli ,

Could you maybe raise the PR for it? It would be great.

**Comment by mehrdad-abdoli** [comment]
@butomo1989 
PR is created : https://github.com/butomo1989/docker-android/pull/51

**Comment by eyal919** [comment]
Is this ready yet? 
It will be nice to do something like:

function start() {
    mkdir -p $VIDEO_PATH
    **name="$(curl -s localhost:4723/wd/hub/sessions | jq -r '.value[0].capabilities.videoName').mp4"**
    echo "Start video recording"
    ffmpeg -video_size 1599x899 -framerate 15 -f x11grab -i $DISPLAY $VIDEO_PATH/$name -y
}
