### ISSUE TITLE
Getting to noVNC from a remote machine

### ISSUE THREAD

**Issue by mike75rock** [butomo1989/docker-android#45]
Hi,

I cannot figure out how to get to the noVNC page of a device from a remote machine.
For example the real IP of the host is 123.45.67.89.
So Selenium Hub is located in 123.45.67.89:4444
There are 3 nodes in Selenium Hub
- host: 172.12.0.6
- host: 172.12.0.7
- host: 172.12.0.8
noVNC is running on port 6080 of each host.

How can I get to noVNC stream from a remote machine?

Thanks in advance!

**Comment by butomo1989** [comment]
Hi @mike75rock , 

You need to find out the docker host IP address of each machine. Please join the chat room so we can discuss there: https://gitter.im/butomo1989/docker-android. I will close this issue, because I think it is not an issue.
