### ISSUE TITLE
Outdated emulator in image with Android version 5.1.1

### ISSUE THREAD

**Issue by SvetA95** [butomo1989/docker-android#46]
How can I resolve this?

**Comment by butomo1989** [comment]
Hi @SvetA95 , 

Thank you for the issue. Could you more specific what do you mean with outdated emulator? and is it arm or x86 image?

**Comment by SvetA95** [comment]
Hi
I'm using your image to automate tests for Android. Today the test ran I got an error saying: Original error: Could not find a connected Android device.

After that I went inside the container and tried to start the emulator manually and got:
emulator: Listening for console connections on port: 5554
emulator: Serial number of this emulator (for ADB): emulator-5554
[140245043508992]:WARNING:./android/base/files/IniFile.cpp:158:Failed to process .ini file /root/.android/emu-update-last-check.ini for reading.
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android SDK Tools" checkbox
 - Click "OK"

[140245120202496]:WARNING:./android/base/files/IniFile.cpp:158:Failed to process .ini file /root/.android/emu-update-last-check.ini for reading.

**Comment by butomo1989** [comment]
Thank you, I will check it later. is it x86 or arm image? @SvetA95

**Comment by SvetA95** [comment]
Yes , butomo1989/docker-android-x86-5.1.1

**Comment by butomo1989** [comment]
Hi @SvetA95 , 

I cannot reproduce the error. I just checked it and it works fine with x86 image for version 5.1.1? my command was `docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container butomo1989/docker-android-x86-5.1.1`. Could you tell me how you run the container?

**Comment by SvetA95** [comment]
Hi @butomo1989 

I'm using a docker-compose file with the following container configs:
   android:
      build:
        context: docker/android
        dockerfile: Dockerfile
      privileged: true
      volumes:
          - ./tests:/usr/src/MRA_Android_App/tests
      links:
          - "db:database"
          - "server"
      ports:
          - "4723:4723"
          - "5554:5554"
          - "5555:5555"
      privileged: true
      tty: true
      environment:
          - DEVICE=Nexus 7
          - APPIUM=true
      container_name: android_appium_tests

Dockerfile:
FROM butomo1989/docker-android-x86-5.1.1



WORKDIR /usr/src/MRA_Android_App

COPY supervisord.conf /usr/src/MRA_Android_App

# install php
RUN apt-get update && apt-get install -y \
        php7.0 \
        php7.0-bcmath \
        php7.0-cli \
        php7.0-common \
        php7.0-fpm \
        php7.0-gd \
        php7.0-gmp \
        php7.0-intl \
        php7.0-json \
        php7.0-mbstring \
        php7.0-mcrypt \
        php7.0-mysqlnd \
        php7.0-pdo \
        php7.0-xml \
        php7.0-curl \
        php7.0-zip \
        php7.0-dev \
        x11vnc \
        telnet \
        expect \
            supervisor

# Install composer

COPY composer.json /usr/src/MRA_Android_App
COPY install_Composer.sh /usr/src/MRA_Android_App
RUN chmod +x /usr/src/MRA_Android_App/install_Composer.sh
RUN /usr/src/MRA_Android_App/install_Composer.sh
COPY emulator_Auth_Token.sh /usr/src/MRA_Android_App
RUN chmod +x /usr/src/MRA_Android_App/emulator_Auth_Token.sh

I am also able to start the container normally. The problem is when I go inside and try to start the emulator. Then I received the error mentioned in the previous post: 
emulator: Listening for console connections on port: 5554
emulator: Serial number of this emulator (for ADB): emulator-5554
[140245043508992]:WARNING:./android/base/files/IniFile.cpp:158:Failed to process .ini file /root/.android/emu-update-last-check.ini for reading.
Your emulator is out of date, please update by launching Android Studio:

    Start Android Studio
    Select menu "Tools > Android > SDK Manager"
    Click "SDK Tools" tab
    Check "Android SDK Tools" checkbox
    Click "OK"

[140245120202496]:WARNING:./android/base/files/IniFile.cpp:158:Failed to process .ini file /root/.android/emu-update-last-check.ini for reading.

**Comment by butomo1989** [comment]
Hi @SvetA95 , 

It looks like you extend the existing docker image that I provide. maybe we can discuss in https://gitter.im/butomo1989/docker-android so I can help you and I can close this issue. :)

**Comment by SvetA95** [comment]
Sure, but the fact that I have extended the image shouldn't matter right? The emulator comes from your docker image and me installing php inside the container along side it, shouldn't have anything to do with the error I'm getting

**Comment by butomo1989** [comment]
hm.. Could you run the original docker image that I provide? does it work in your machine? if yes, I assume there is misconfiguration in the Dockerfile where you extend the functionalities from the original image. if not, please provide the logs.

**Comment by butomo1989** [comment]
the logs could be found in /var/log/supervisor/ inside container @SvetA95

**Comment by SvetA95** [comment]
It worked in the base image, thanks. I'll try and figure out what's wrong with my setup. Closing the issue,

**Comment by butomo1989** [comment]
Let me know if you need any help. we can discuss it through bitter @SvetA95
