### ISSUE TITLE
Failure connecting to appium

### ISSUE THREAD

**Issue by pesekviktor** [butomo1989/docker-android#58]
Hi, 
I am new to docker and I am trying to run the example test from https://github.com/testvagrant/AppiumDemo using docker-android.

On ubuntu 16.04LTS I run the command from tutorial to start docker with appium passing the apk.

`docker run --privileged -d -p 6080:6080 -p 4723:4723 -p 5554:5554 -p 5555:5555 -v /home/vikky/flipkart.apk:/root/tmp -e DEVICE="Nexus 5" -e APPIUM=True -e CONNECT_TO_GRID=True -e APPIUM_HOST="127.0.0.1" -e APPIUM_PORT=4723 -e SELENIUM_HOST="172.17.0.1" -e SELENIUM_PORT=4444 --name android-container butomo1989/docker-android-x86-7.1.1`

 In the browser on localhost:6080 I can see the virtual phone and appium server. With some error, but I figured those might be caused by the phone booting.

![image](https://user-images.githubusercontent.com/33232478/34548309-a7c0c6e0-f101-11e7-9580-61f92f39b501.png)

I use `docker exec -it android-container tail -f /var/log/supervisor/docker-android.stdout.log`

_[29] [ INFO] app - Run appium server...
[29] [ INFO] app - Connect to selenium grid? True
[29] [ INFO] app - Appium node config: {'configuration': {'port': 4723, 'url': 'http://127.0.0.1:4723/wd/hub', 'unregisterIfStillDownAfter': 120000, 'register': True, 'hubPort': 4444, 'proxy': 'org.openqa.grid.selenium.proxy.DefaultRemoteProxy', 'hubHost': '172.17.0.1', 'maxSession': 6, 'timeout': 30000, 'registerCycle': 5000, 'cleanUpCycle': 2000, 'host': '127.0.0.1'}, 'capabilities': [{'browserName': 'android', 'platformName': 'Android', 'version': '7.1.1', 'platform': 'Android', 'deviceName': 'nexus_5_7.1.1', 'maxInstances': 1}]}
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"_

OK, emulator is out of date, but it could still work. So I updated the connection class in https://github.com/testvagrant/AppiumDemo to have same capabilities:

`     
DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("browserName", "android");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("version", "7.1.1");
        capabilities.setCapability("platform", "Android");
        capabilities.setCapability("deviceName", "nexus_5_7.1.1");
        capabilities.setCapability("maxInstances", "1");
        capabilities.setCapability("app", "/Users/nishant/Development/AppiumDemo/apps/flipkart.apk");
        capabilities.setCapability("appPackage", "com.flipkart.android");
        capabilities.setCapability("appActivity", "com.flipkart.android.SplashActivity");
        driver = new AndroidDriver(new URL("hhttp://172.17.0.1:4444/wd/hub"), capabilities);
   `
Which gives me rather uninformative error:

org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=/Users/nishant/Development/AppiumDemo/apps/flipkart.apk, appPackage=com.flipkart.android, appActivity=com.flipkart.android.SplashActivity, appium-version=1.0, platformVersion=5.0, platformName=Android, deviceName=Nexus}], required capabilities = Capabilities [{}]

Could you please help me locate the issue?

**Comment by butomo1989** [comment]
Hi @pesekviktor , 

from the logs I can see that there is a problem with the connection between Appium server and selenium hub (network issue). for quick fix you can use Appium server directly without connecting to selenium grid. you can also ask in our group chat group if you have further question in the future: https://gitter.im/butomo1989/docker-android. 

I will close this issue because it seems just a question. but please fell free to reopen it if there is a bug or feature request.

**Comment by pesekviktor** [comment]
Hi, yes, it is a question. Sorry for writing it to a wrong place, I will ask in group chat after trying out straight with appium
