### ISSUE TITLE
unicodekeyboard is not working for fa_IR

### ISSUE THREAD

**Issue by mehrdad-abdoli** [butomo1989/docker-android#60]
hi @butomo1989 
i have set unicodekeyboard=true in capabilities and  installed UnicodeIME-debug (enable and set default) by:
adb install /media/UnicodeIME-debug.apk
adb shell ime enable io.appium.android.ime/.UnicodeIME
adb shell ime set io.appium.android.ime/.UnicodeIME

but when test my app it do not input unicode text at all with no error in appium.
do you have any idea?

**Comment by butomo1989** [comment]
Hi @mehrdad-abdoli , 

Could you check in normal emulator from your local machine? because I think it could be 2 things: wrong set up or an issue in emulator itself. You could ask to our gitter group as well, there might be someone who can help you.

**Comment by butomo1989** [comment]
I will close this PR because there is no response. Please feel free to reopen it.
