### ISSUE TITLE
APPIUM_HOST Ignored in .yml

### ISSUE THREAD

**Issue by rlupo09** [butomo1989/docker-android#64]
APPIUM_HOST as an environment variable in the .yml does nothing

Example .yml

version: '3.3'

services:
  hub:
    image: selenium/hub
    ports:
      - "4450:4450"
    environment:
      - GRID_BROWSER_TIMEOUT=60000
      - GRID_TIMEOUT=90000
      - GRID_MAX_SESSION=50
      - GRID_CLEAN_UP_CYCLE=60000
      - GRID_UNREGISTER_IF_STILL_DOWN_AFTER=180000
      - GRID_NEW_SESSION_WAIT_TIMEOUT=120000
    entrypoint: bash -c 'SE_OPTS="-port 4450" /opt/bin/entry_point.sh'

  SamsungGalaxyS6:
    image: butomo1989/docker-android-arm-7.1.1
    ports:
      - 6080:6080
    environment:
      - Device="Samsung Galaxy S6"
      - APPIUM=True
      - CONNECT_TO_GRID=True
      - SELENIUM_HOST=hub
      - SELENIUM_PORT=4450
      - APPIUM_HOST:10.57.85.10

Observed result: The appium host is not set to 10.57.85.10

Note: To run on a docker swarm one must be able to set the APPIUM_HOST to $$HOSTNAME

![screen shot 2018-02-09 at 3 16 04 pm](https://user-images.githubusercontent.com/23666924/36050681-13f359be-0dad-11e8-8991-3b0ed289e782.png)

**Comment by butomo1989** [comment]
Hi @rlupo09 , 

you used a wrong symbol. try to replace symbol : with =. Could you close the issue if it works? :)

**Comment by rlupo09** [comment]
Hi butomo,

The = was the issue. I should have caught that, I apologize. 

Thank you
