### ISSUE TITLE
I want to start x86 emulator on mac os

### ISSUE THREAD

**Issue by Caroline0071** [butomo1989/docker-android#66]
I want to start x86 emulator with docker image on mac os.
Why not support?
How to start up x86 android emulator on mac os with docker image?

**Comment by diemol** [comment]
Hi @Caroline0071

Did you check the Quick Started section? https://github.com/butomo1989/docker-android#quick-start

It is possible but it is very slow.

**Comment by butomo1989** [comment]
Hi  @Caroline0071 , 

It is because there was issues with HAXM and KVM. if you want to use x86 on Mac, you can give a try by using VM.

**Comment by Caroline0071** [comment]
hi @butomo1989 
So docker images is not support to run android x86 emulator.
And I think also that it's a issues  compatibility mac kernel with docker.
My idea was setting up android x86 emulator in the docker to excute UI automation.

**Comment by HasBert** [comment]
Hey guys,
I tried to run the android emulator inside Virtualbox 6.x inside a Ubunu 18.04 guest os and I didn't get it to work. I searched for some advises how to maybe enable KVM inside the guest os, but the only thing I found was [this](https://stackoverflow.com/questions/53778106/how-to-enable-kvm-on-a-mac-for-qemu). So as I'm reading this correctly KVM is not supported on OSX? Are there other ways to virtualize the x86 emulator?

@Caroline0071 Have you managed the virtualization now? Would you share your researche?
@diemol Do you have any instructions besides using a software like Virtualbox?

**Comment by diemol** [comment]
The only way I know to run something with KVM on OSX is by using something like Parallels or VMWare Fusion (both paid with free trials). Sadly, I think there is not a free software that allows you to do that.

**Comment by HasBert** [comment]
@diemol thank you for your response. :kissing_heart: Maybe I'll give it a try. 
@budtmo do you have some experience with this topic? Shouldn't we update the documentation if this isn't working on OSx without using paid software? I'm not 100% sure if there maybe is a way to get it to work, but I need to spend more time on it.
Thanks for your time :wink:
