### ISSUE TITLE
Getting "unable to remove port forward" and "Error executing adbExec" errors

### ISSUE THREAD

**Issue by jk79** [butomo1989/docker-android#67]
I'm trying to setup simple test against docker-android solution. I tried different emulators and still no-go.

I'm using this as a test package: 
https://github.com/appium/sample-code/tree/master/sample-code/examples/node

Started server with following command:
`docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -p 4723:4723 -e DEVICE="Samsung Galaxy S6" -e APPIUM=True --name android-container butomo1989/docker-android-arm-5.1.1`

Environment: Mac

Capabilities:
`exports.android19 = {
  browserName: '',
  'appium-version': '1.3.4',
  platformName: 'Android',
  platformVersion: '5.1.1',
  automationName: 'UiAutomator2',
  deviceName: 'Samsung Galaxy S6',
    noReset: 'true',
  app: undefined // will be set later
};`

And full log:
![screen shot 2018-02-13 at 12 29 44](https://user-images.githubusercontent.com/3685074/36149950-adffeaa4-10b9-11e8-9a4b-27f3b2112ac3.png)
![screen shot 2018-02-13 at 12 30 03](https://user-images.githubusercontent.com/3685074/36149955-b30d935c-10b9-11e8-86d4-bcd241a20fc0.png)

**Comment by butomo1989** [comment]
Hi @jk79 , 

It is because of timeout. I can suggest 2 options:
1. you wait until the emulator is ready before you run test if you use arm image (normally it takes around 10 min to make emulator ready for arm image) OR
2. you use x86 image with better performance in VM if you don’t use Linux machine

I will close this issue for now. Please feel free to reopen it.

**Comment by jk79** [comment]
Hi @butomo1989, that works great.
I'm now able to run the tests on my Mac, I'll be porting this out to Jenkins CentOS machine, hope it will work there as well. 
Good work, keep it up!

**Comment by butomo1989** [comment]
@jk79 I am happy that I can help. :) Don’t forget to give a star to the project. :b

**Comment by jk79** [comment]
My pleasure, just starred it.

**Comment by timsheng** [comment]
@jk79 did you choose the solution #1 or #2 to fix this problem, i have met the same issue.

**Comment by timsheng** [comment]
actually, I was waiting emulator to be ready for about 30 minutes, but it kept launching.
when I run my script, it return ```ERROR: An unknown server-side error occurred while processing the command. Original error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/root/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk' timed out after 20000ms'; Stderr: ''; Code: 'null'```

@butomo1989 i will try to use solution 2 , hope it works fine.

**Comment by timsheng** [comment]
when I use x86 image in VM on mac, it prompt error message

**Comment by jk79** [comment]
@timsheng, there were couple of issues. First, I had to close Docker, it somehow interfere. Secondly, I used 5.1.1 image and it was working fine for me.

**Comment by timsheng** [comment]
@jk79 thanks for your quick response, that's interesting, I never try close Docker, i will try
except 5.1.1 image, did you try others arm images, i tried 6.0 and 7.1.1 , both of them failed , the same error message with you paste in this ticket
