### ISSUE TITLE
Black screen after running the docker (arm image)

### ISSUE THREAD

**Issue by moradkh** [butomo1989/docker-android#69]
**Please make sure that it is an issue / a feature request. If it is a question / help wanted, please visit [our group chat](https://gitter.im/butomo1989/docker-android). Thank you!**

Operating System: Mac Sierra 10.12.6

Docker Image: butomo1989/docker-android-arm-7.1.1

Docker Version:  1.19.0

Docker Command to start docker-android:  

docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Nexus s" -e APPIUM=True --name android-container butomo1989/docker-android-arm-7.1.1
  
## Expected Behavior
When i run the docker and then I go the the 127.0.0.1:6080 in my local machine, I get black screen, 
also when I run adb devices inside the docker container, I get nothing 

> OSXICGIT072:~ mk90106$ docker run -it butomo1989/docker-android-arm-7.1.1 bash
> root@5c65fde9a15b:~# adb devices
> List of devices attach
![screen shot 2018-02-26 at 3 40 02 pm](https://user-images.githubusercontent.com/1182988/36673455-8773f1b2-1b0b-11e8-8362-6fd32c1efaad.png)
ed
> 
> root@5c65fde9a15b:~#

## Actual Behavior
1. Need to find the device in the docker image.
2. Need to see the UI of the screen using the noVnc in my hosted localhost.

Any suggestions ?

**Comment by CapDam** [comment]
Hi, 

I have the same problem...

Logs:
`2018-02-26 08:18:15,932 CRIT Supervisor running as root (no user in config file)
2018-02-26 08:18:15,936 INFO supervisord started with pid 5
2018-02-26 08:18:16,940 INFO spawned: 'xvfb' with pid 8
2018-02-26 08:18:16,942 INFO spawned: 'port-forward' with pid 9
2018-02-26 08:18:16,945 INFO spawned: 'novnc' with pid 10
2018-02-26 08:18:16,947 INFO spawned: 'openbox' with pid 11
2018-02-26 08:18:16,949 INFO spawned: 'x11vnc' with pid 12
2018-02-26 08:18:16,950 INFO spawned: 'android-screen-mirror' with pid 13
2018-02-26 08:18:16,952 INFO spawned: 'docker-appium' with pid 14
2018-02-26 08:18:16,954 INFO spawned: 'auto-recording' with pid 15
2018-02-26 08:18:16,979 INFO success: android-screen-mirror entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-02-26 08:18:16,985 INFO exited: android-screen-mirror (exit status 0; expected)
2018-02-26 08:18:18,051 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-26 08:18:18,051 INFO success: port-forward entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-26 08:18:18,051 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-26 08:18:18,051 INFO success: openbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-26 08:18:18,051 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-26 08:18:18,051 INFO success: docker-appium entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-26 08:18:18,051 INFO success: auto-recording entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-26 08:18:23,012 INFO exited: auto-recording (exit status 0; expected)`

**Comment by mmineo-ds** [comment]
Me too, using a Mac High Sierra (latest version)
I ran 
➜  ~ docker exec -it android-container tail -f /var/log/supervisor/docker-android.stdout.log

And I got this log: 
```
System image: armeabi-v7a
Image type: google_apis
[28] [ INFO] app - Device: Nexus 5
[28] [ INFO] app - AVD name: nexus_5_7.1.1
[28] [ INFO] app - Preparing emulator...
[28] [ INFO] app - Command to create avd: avdmanager create avd -f -n nexus_5_7.1.1 -b google_apis/armeabi-v7a -k "system-images;android-25;google_apis;armeabi-v7a" -d Nexus\ 5 -p /root/android_emulator
[28] [ INFO] app - Skin was added in config.ini
[28] [ INFO] app - Run emulator...
[28] [ INFO] app - Run appium server...
[28] [ INFO] app - Connect to selenium grid? False
emulator: warning: opening audio output failed

Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"
```

**Comment by dorangao** [comment]
+1, using a Mac High Sierra (latest version)
Same behaviors for all different versions (arm) tried.

**Comment by thelittlefireman** [comment]
Same issue for me but on Synology server (unix base)

**Comment by richardpenman** [comment]
Same for me on Mac Sierra 10.12.6 - all arm versions I tried have blank screen.

**Comment by butomo1989** [comment]
I think the issue comes from the emulator. We will try to update the emulator version. please consider to use x86 image. If you are using windows or OSX, you can run it under VMWare. It is faster than arm image and besides I won't support arm image in the future because of the its performance.

**Comment by greenerchen** [comment]
I have a workaround. You may exit the emulator first. Open a terminal emulator and start an emulator again using command line.
```
$ emulator -avd <emulator_name> -gpu off -noaudio
```
The emulator name in this case is `nexus_5_7.1.1`.
Then wake up the emulator by clicking the power button on the panel.

**Comment by s417-lama** [comment]
I had the same issue on Ubuntu 16.04.
In the case of me, this is because I started the emulator with VirtualBox running. The emulator cannot start with VirtualBox or VMWare running, so I had to shutdown VirtualBox.

**Comment by Kignuf** [comment]
I'm experiencing the same issue.
MacOSX 10.13.3
Docker 18.03.0-ce, build 0520e24

Logcat logs (see timestamps to grasp how slow it is)
https://gist.github.com/Kignuf/28b12ad490e243fbd18e186d2c17c909

**Comment by Shinoby1992** [comment]
i have this issue running on a ubuntu 16 vm 
its get unhealthy and black screen when i connect to the vnc 
log file

`10 16:11:39,140 CRIT Supervisor running as root (no user in config file)
,
10 16:11:39,152 INFO supervisord started with pid 5
,
10 16:11:40,154 INFO spawned: 'xvfb' with pid 8
,
10 16:11:40,157 INFO spawned: 'port-forward' with pid 9
,
10 16:11:40,159 INFO spawned: 'novnc' with pid 10
,
10 16:11:40,162 INFO spawned: 'openbox' with pid 11
,
10 16:11:40,170 INFO spawned: 'x11vnc' with pid 12
,
10 16:11:40,181 INFO spawned: 'android-screen-mirror' with pid 13
,
10 16:11:40,189 INFO spawned: 'docker-appium' with pid 14
,
10 16:11:40,207 INFO spawned: 'auto-recording' with pid 22
,
10 16:11:40,208 INFO exited: android-screen-mirror (exit status 0; expected)
,
10 16:11:41,171 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:11:41,171 INFO success: port-forward entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:11:41,171 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:11:41,171 INFO success: openbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:11:41,171 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:11:41,232 INFO success: docker-appium entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:11:41,233 INFO success: auto-recording entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:11:46,331 INFO exited: auto-recording (exit status 0; expected)
,
10 16:12:31,136 INFO exited: docker-appium (exit status 0; expected)
,
10 16:12:45,045 CRIT Supervisor running as root (no user in config file)
,
10 16:12:45,072 INFO supervisord started with pid 6
,
10 16:12:46,076 INFO spawned: 'xvfb' with pid 9
,
10 16:12:46,078 INFO spawned: 'port-forward' with pid 10
,
10 16:12:46,095 INFO spawned: 'novnc' with pid 11
,
10 16:12:46,103 INFO spawned: 'openbox' with pid 12
,
10 16:12:46,133 INFO spawned: 'x11vnc' with pid 13
,
10 16:12:46,180 INFO spawned: 'android-screen-mirror' with pid 14
,
10 16:12:46,271 INFO spawned: 'docker-appium' with pid 22
,
10 16:12:46,343 INFO spawned: 'auto-recording' with pid 27
,
10 16:12:46,384 INFO success: android-screen-mirror entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
,
10 16:12:46,486 INFO exited: android-screen-mirror (exit status 0; expected)
,
10 16:12:47,284 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:12:47,285 INFO success: port-forward entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:12:47,285 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:12:47,285 INFO success: openbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:12:47,285 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:12:47,285 INFO success: docker-appium entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:12:47,316 INFO success: auto-recording entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
,
10 16:12:52,591 INFO exited: auto-recording (exit status 0; expected)
,
10 16:13:41,079 INFO exited: docker-appium (exit status 0; expected)
,`

**Comment by Nedervino** [comment]
+1, using MacOSX High Sierra (10.13.4) and with the exact same logs as CapDam. @butomo1989 any update on a possible fix that doesn't require a hypervisor?

**Comment by moradkh** [comment]
any update ? I can help with this

**Comment by butomo1989** [comment]
Hi @Nedervino @moradkh ,

Please use VMWare to run x86 image, because the performance of arm image is really slow and cause a lot of issues so it would be great if you can investigate it and create PR.

**Comment by pasqualevitale** [comment]
VMWare (as all hypervisor) are not able to run KVM, and x86 requires KVM, so you have to use a working image of emulator with arm for VMs

**Comment by butomo1989** [comment]
For windows you can try VMWare player. I tried it last time and it works. for Mac please take a look in readme how it works, somebody contributed to the documentation last time.

**Comment by butomo1989** [comment]
I will close this issue, because I will not support arm image in the future. Please use VM that support virtualization to be able to run x86 image.
