### ISSUE TITLE
Support real device

### ISSUE THREAD

**Issue by butomo1989** [butomo1989/docker-android#7]
Able to recognise real device from docker-container and mirror device screen to noVNC. this feature will be combine with #6

**Comment by butomo1989** [comment]
https://github.com/adakoda/android-screen-monitor

**Comment by andrcuns** [comment]
@butomo1989 Did You start working on this already? Since I'm involved in mobile device specific testing project now, it might be interesting for me to look in to this as well since it could be quite useful.

**Comment by butomo1989** [comment]
no, I haven't started it @andrcuns. awesome! yeah, of course, your help is very welcome.

**Comment by andrcuns** [comment]
Cool, if and when I have time, I will try to take a look at this feature.

**Comment by butomo1989** [comment]
Implemented in release version 0.8
