### ISSUE TITLE
Feature : Add architecture capabilities x86_64, armeabi-v7a, arm64-v8a

### ISSUE THREAD

**Issue by thelittlefireman** [butomo1989/docker-android#88]
**Please make sure that it is an issue / a feature request. If it is a question / help wanted, please visit [our group chat](https://gitter.im/butomo1989/docker-android). Thank you!**

Operating System: 
All

Docker Image:
all

Docker Version:  
17.09

Docker-compose version (Only if you use it):  

Docker Command to start docker-android:  

  
## Expected Behavior
Using x86, x86_64, armeabi-v7a, arm64-v8a

## Actual Behavior
Using X86

Could it be possible to generate image for multiple Archi ? Actualy if i look right, we only use x86 image.
Could we generate containers  for x86_64, armeabi-v7a, arm64-v8a

use this system images : 
  system-images;android-24;google_apis;arm64-v8a                                           | 22           | Google APIs ARM 64 v8a System Image                                
  system-images;android-24;google_apis;armeabi-v7a                                         | 22           | Google APIs ARM EABI v7a System Image                              
  system-images;android-24;google_apis;x86                                                 | 22           | Google APIs Intel x86 Atom System Image                            
  system-images;android-24;google_apis;x86_64  

I'm pretty sure it will help for resolving issue for person who have black-screen issue or no hardware acceleration enable possibility (due to hardware limitation Synology OS, etc ) , etc #69 #75 

Not huge work is needed, just this line [https://github.com/butomo1989/docker-android/blob/4975ebcc47e020c2395e3a841e43cb1f28c451ed/release.sh#L59](https://github.com/butomo1989/docker-android/blob/4975ebcc47e020c2395e3a841e43cb1f28c451ed/release.sh#L59) 

Just need to overload the "processor" variable with "x86", "x86_64", arm ....

Actualy i'have not time to do this but maybe later

**Comment by JoeSSS** [comment]
Moreover, the last 3 API levels do not have ARM and others. So I believe that it is not supported from google as well.

**Comment by aleksandrawy** [comment]
Hi, I have a question about supporting x86 by Mac. When I create the emulator ex. simply from Android Studio and I choose the x86 ABI , I can run the created emulator without any problems (on macOS High Sierra). Can you explain me what is the difference between the android images that are available to get in Docker and those from ex. Android Studio?

**Comment by JoeSSS** [comment]
The difference is the OS. On mac you can use HAXM which is supported by Mac's CPU. In its turn, the docker runs on linux which supports only kvm and kvm is not compatible with mac CPU.. So, there is no other ways around rather than create a Linux VM on your mac and run it there. 

What we're doing in my company, is creating virtual device farm using this image and providing up to 16 devices running on remote Linux machine, so people are actually happy to do not run emulator on their Macs :)

**Comment by aleksandrawy** [comment]
I want to use several emulator with different APIs to run the automated tests of application. I want to run them on Jenkins. Until now I run only one emulator and I wanted to dockerize it to run more than one emulator with own environments (appium server etc.). Jenkins is set on the Mac in my company and now I don't know how to run those automated tests on the several APIs. Should I create VM on each run or what? Do you have any ideas?

**Comment by v3g3t4x** [comment]
@JoeSSS have you performance issue with your 16 devices ?

**Comment by JoeSSS** [comment]
@v3g3t4x not that I know about. But you should have a powerful machine for that ;) For example my previous nodes could handle just 8 connections (it was 16 cores 16gb ram). Current ones are 48 cores and 150gb RAM, which is more than enough. So we even opened 4 executors more for app compile.
