### ISSUE TITLE
Android emulator is been created on every run

### ISSUE THREAD

**Issue by red-avtovo** [butomo1989/docker-android#91]
Not an issue, but mostly a question.
I'm currently working on fix for #87 and I got an idea to split script logic between cases, when you call for `docker run` and `docker start`.
Do we really need to recreate an emulator every time, we run a container? We can improve boot time by creating the emulator instance just once.

**Comment by red-avtovo** [comment]
Every time we start container, we execute `/src/appium.sh`, which executes `python3 -m src.app`, which forcibly creates new emulator instance.
I would like to add condition and remove emulator creation if we just restarted our container

**Comment by butomo1989** [comment]
sure, sounds good to me. Thank you @red-avtovo

**Comment by butomo1989** [comment]
Fixed in release [1.2](https://github.com/butomo1989/docker-android/releases/tag/1.2)
