### ISSUE TITLE
GIT: could git be incorporated inside all images by default?

### ISSUE THREAD

**Issue by marad9016100** [butomo1989/docker-android#94]
Docker Image:
All or butomo1989/docker-android-x86-7.1.1 and all newer.

Can git 
(apt-get update && apt-get install git) be added to the images by default?
It could be quite useful when using jenkins docker plugins and git repos.

Thank you,
Mariusz

**Comment by butomo1989** [comment]
Hi @marad9016100 , 

It is not needed. You can clone the repo outside the container and share the volume to the container. You can read it [here](https://docs.docker.com/storage/volumes/). I will close the issue. For further question, please use our group chat.
