### ISSUE TITLE
Unhealthy because of allow USB debugging on 8.1

### ISSUE THREAD

**Issue by mehrdad-abdoli** [butomo1989/docker-android#98]
Operating System: 
Ubuntu 16.04

Docker Image:
butomo1989/docker-android-x86-8.1

Docker Version:  
18.05.0-ce, build f150324

Docker-compose version (Only if you use it):  
1.17.1, build 6d101fb

## Expected Behavior
healthy dockers

## Actual Behavior
It show docker on unhealthy forever until I allow USB debugging on emulator from vnc
![image](https://user-images.githubusercontent.com/22414520/43002221-408590f0-8c3d-11e8-9592-d965990a7b6e.png)

**Comment by JoeSSS** [comment]
It should be fixed with the latest PR merge

**Comment by mehrdad-abdoli** [comment]
@JoeSSS when It will be done ? can you send me the commit so I change my server manualy?

**Comment by JoeSSS** [comment]
It is on master. This PR: https://github.com/butomo1989/docker-android/pull/97

**Comment by butomo1989** [comment]
#97 contains the refactoring of the code only. try #96 @mehrdad-abdoli 
and this ticket is duplicated with #87 so I will close it but feel free to reopen it.
